version: "3.0"
services:
  timescale:
    image: timescale/timescaledb:2.10.3-pg15-oss
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./timescale/init/003_schema.sql:/docker-entrypoint-initdb.d/003_schema.sql
      - ./timescale/init/004_data.sh:/docker-entrypoint-initdb.d/004_data.sh
      - ./data/kpi.csv.gz:/tmp/kpi.csv.gz
      - ./data/kpi_type.csv.gz:/tmp/kpi_type.csv.gz
  grafana:
    image: grafana/grafana:9.5.2
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/home.json
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards      