apiVersion: 1

datasources:
  - name: Timescale
    type: postgres
    url: timescale:5432
    user: postgres
    isDefault: true
    secureJsonData:
      password: 'postgres'
    jsonData:
      database: postgres
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: true